### PR TITLE
Updated huntPastebin.py

### PR DESCRIPTION
**Pull request by evilgensec**
Added a progress bar.

### CODE REVIEW

**Review by prdp1137 — APPROVED** [review]

**Comment by prdp1137** [comment]
@evilgensec  thank you for the contribution!

**Comment by evilgensec** [comment]
xss2

**Comment by evilgensec** [comment]
xss3

**Comment by evilgensec** [comment]
xss2

**Comment by evilgensec** [comment]
xss_metadata

**Pull request merged**
